# openapi.yaml
openapi: 3.0.3
info:
  title: Xima CCaaS License Provisioning API
  description: |
    API for authorized resellers to provision and manage CCaaS licenses.

    **Important Security Note:**

    The `/v1/licensing` endpoint requires strict adherence to payload ordering and signature generation procedures.  See the endpoint documentation for details.
  version: 1.0.0
tags:
  - name: License Management
servers:
  - url: https://api.ximadev.cloud/v1
    description: Sandbox API server for testing

# Reference external files
components:
  securitySchemes:
    bearerAuth:
      $ref: './components/security.yaml#/bearerAuth'

  schemas:
    Error:
      $ref: './components/schemas.yaml#/Error'
    LicenseUpdateRequest:
      $ref: './components/schemas.yaml#/LicenseUpdateRequest'
    LicenseUpdateResponse:
      $ref: './components/schemas.yaml#/LicenseUpdateResponse'

# Paths are referenced from external files
paths:
  /licensing:
    $ref: './paths/licensing.yaml'