# openapi.yaml
openapi: 3.0.3
info:
  title: Xima CCaaS License Provisioning API
  description: |
    API for authorized resellers to provision and manage CCaaS licenses using industry-standard JWT authentication with certificate fingerprint-based Key IDs.

    **Important Security Note:**

    The `/v1/licensing` endpoint requires JWT authentication following RFC 7515 (JSON Web Signature) and RFC 7517 (JSON Web Key) standards with certificate fingerprint-based `kid` claims. See the authentication documentation for details.

    **JWKS Endpoint:** `/licensing/.well-known/jwks.json`
  version: 1.0.0
tags:
  - name: License Management
servers:
  - url: https://api.ximadev.cloud/v1
    description: Sandbox API server for testing

# Reference external files
components:
  securitySchemes:
    bearerAuth:
      $ref: './components/security.yaml#/bearerAuth'

  schemas:
    Error:
      $ref: './components/schemas.yaml#/Error'
    LicenseUpdateRequest:
      $ref: './components/schemas.yaml#/LicenseUpdateRequest'
    LicenseUpdateResponse:
      $ref: './components/schemas.yaml#/LicenseUpdateResponse'
    LicenseDeleteRequest:
      $ref: './components/schemas.yaml#/LicenseDeleteRequest'
    LicenseDeleteResponse:
      $ref: './components/schemas.yaml#/LicenseDeleteResponse'

# Paths are referenced from external files
paths:
  /v1/licensing/update:
    $ref: './paths/licensing.yaml'